###########
# Dataset #
###########

data_root: './data'
batch_size: 10
num_workers: 16
sleep_batch_size: 50
sleep_num_workers: 4
eval_batch_size: 256
eval_num_workers: 4

label_offset:
  mnist: 0

#########
# Model #
#########

x_c: 1
x_h: 28
x_w: 28
y_c: 10

device: 'cuda'

model_name: 'ndpm_model'
g: 'mlp_sharing_vae'
d: 'mlp_sharing_classifier'
disable_d: False
vae_nf_base: 64
vae_nf_ext: 16
cls_nf_base: 64
cls_nf_ext: 16
z_dim: 16
z_samples: 16

recon_loss: 'gaussian'
x_log_var_param: 0
learn_x_log_var: false
classifier_chill: 0.01


#########
# DPMoE #
#########

known_destination: [1, 1, 2, 2, 3, 3, 4, 4, 5, 5]
log_alpha: -400
stm_capacity: 500
stm_erase_period: 0
sleep_step_g: 8000
sleep_step_d: 2000
sleep_summary_step: 500
sleep_val_size: 0
update_min_usage: 0.1


#########
# Train #
#########

implicit_lr_decay: false
weight_decay: 0.00001

optimizer_g:
  type: Adam
  options:
    lr: 0.0004

lr_scheduler_g:
  type: MultiStepLR
  options:
    milestones: [1]
    gamma: 1.0

optimizer_d:
  type: Adam
  options:
    lr: 0.0001

lr_scheduler_d:
  type: MultiStepLR
  options:
    milestones: [1]
    gamma: 1.0

clip_grad:
  type: value
  options:
    clip_value: 0.5


########
# Eval #
########

eval_d: False
eval_g: False
eval_t: True

###########
# Summary #
###########

summary_step: 250
eval_step: 250
summarize_samples: False
